### ISSUE TITLE
AllJoyn Explorer is broked when object registered with AJ_OBJ_FLAG_DESCRIBED 

### ISSUE THREAD

**Issue by demon-xxi** [ms-iot/samples#150] opened 2015-11-09 07:52 UTC
When alljoyn object is registered with AJ_OBJ_FLAG_DESCRIBED or with (AJ_OBJ_FLAG_DESCRIBED  | AJ_OBJ_FLAG_ANNOUNCED)  then AllJoyn Explorer shows 0 interfaces declared for the object. 

Even though AJ Explorer  does not yet support AllJoyn Events and Actions API, it should respect AJ_OBJ_FLAG_ANNOUNCED  flag present and use basic Introspection interface which is still available for the object.

**Comment by zhuridartem** [comment] 2015-11-17 01:07
Duplicate of https://github.com/ms-iot/samples/issues/151

**Closed as completed** 2015-11-17 18:37 UTC
